### PR TITLE
get list of yast team boards from trello

### PR DESCRIPTION
**Pull request by wfeldt**

### CODE REVIEW

**Comment by mvidner** [comment]
This looks good!
Is it enough? I think the _lists_ have gone out of sync as well, not only the *boards*. See `CHECKED_LISTS`.

**Comment by wfeldt** [comment]
Good point. Is it necessary to limit to certain lists in `#find_trello_bugs`?

**Comment by mvidner** [comment]
I think taking all lists is fine

**Comment by mvidner** [comment]
Thanks Steffen! I have fixed up Rubocop style complaints in PR 18 and merged that one.

**Pull request closed without merging**
